name: Release Theme - Josh

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn build
            - run: yarn test

    publish:
        name: Publish to npm
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn workspace gatsby-theme-portfolio-minimal semantic-release --branches main
              env:
                 NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                 NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                 GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
