name: Release Theme - Josh

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn build
            - run: yarn test

    publish:
        name: Publish to npm
        needs: test
        runs-on: ubuntu-latest
        permissions:
             contents: write # to be able to publish a GitHub release
             issues: write # to be able to comment on released issues
             pull-requests: write # to be able to comment on released pull requests
             id-token: write # to enable use of OIDC for npm provenance
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/
                  scope: '@jhalickman'
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn workspace gatsby-theme-portfolio-minimal semantic-release --branches main
              env:
                 NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                 GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                 GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                 NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
                 NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
